name: KnockbackSync
version: '1.3.2'
main: me.caseload.knockbacksync.KnockbackSync
api-version: '1.18'
authors: [ Caseload, VanillaChanny ]
description: Synchronizes player knockback for smoother gameplay.
folia-supported: true
permissions:
  knockbacksync.update:
    default: op
  knockbacksync.toggle.global:
    default: op
  knockbacksync.toggle.other:
    default: op
  knockbacksync.toggle.self:
    default: op
  knockbacksync.ping:
    default: op